CREATE TABLE basketball_team
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    image_url   VARCHAR(255),
    CONSTRAINT pk_basketball_team PRIMARY KEY (id)
);