CREATE TABLE basketball_game
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance       INT NOT NULL,
    home_team_id BIGINT NOT NULL,
    guest_team_id   BIGINT NOT NULL
);

ALTER TABLE basketball_game
ADD CONSTRAINT fk_game_home_team FOREIGN KEY (home_team_id)
REFERENCES basketball_team (id);

ALTER TABLE basketball_game
ADD CONSTRAINT fk_game_guest_team FOREIGN KEY (guest_team_id)
REFERENCES basketball_team (id);