CREATE TABLE basketball_player
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    euroleague_id              VARCHAR(255),
    first_name                 VARCHAR(255),
    last_name                  VARCHAR(255),
    image_url                  VARCHAR(255),
    average_minutes            DOUBLE PRECISION                        NOT NULL,
    average_points             DOUBLE PRECISION                        NOT NULL,
    average2points_attempted   DOUBLE PRECISION                        NOT NULL,
    average2points_made        DOUBLE PRECISION                        NOT NULL,
    average3points_attempted   DOUBLE PRECISION                        NOT NULL,
    average3points_made        DOUBLE PRECISION                        NOT NULL,
    average_ft_attempted       DOUBLE PRECISION                        NOT NULL,
    average_ft_made            DOUBLE PRECISION                        NOT NULL,
    average_assists            DOUBLE PRECISION                        NOT NULL,
    average_steals             DOUBLE PRECISION                        NOT NULL,
    average_turnovers          DOUBLE PRECISION                        NOT NULL,
    average_rebounds           DOUBLE PRECISION                        NOT NULL,
    average_offensive_rebounds DOUBLE PRECISION                        NOT NULL,
    average_defensive_rebounds DOUBLE PRECISION                        NOT NULL,
    average_plus_minus         DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_basketball_player PRIMARY KEY (id)
);