CREATE TABLE basketball_player (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   averageMinutes DOUBLE PRECISION,
                                   averagePoints DOUBLE PRECISION,
                                   average2PointsAttempted DOUBLE PRECISION,
                                   average2PointsMade DOUBLE PRECISION,
                                   average3PointsAttempted DOUBLE PRECISION,
                                   average3PointsMade DOUBLE PRECISION,
                                   averageFtAttempted DOUBLE PRECISION,
                                   averageFtMade DOUBLE PRECISION,
                                   averageAssists DOUBLE PRECISION,
                                   averageSteals DOUBLE PRECISION,
                                   averageTurnovers DOUBLE PRECISION,
                                   averageRebounds DOUBLE PRECISION,
                                   averageOffensiveRebounds DOUBLE PRECISION,
                                   averageDefensiveRebounds DOUBLE PRECISION,
                                   averagePlusMinus DOUBLE PRECISION
);