CREATE TABLE basketball_player_game
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id          BIGINT,
    game_id            BIGINT,
    minutes            INTEGER                                 NOT NULL,
    points             INTEGER                                 NOT NULL,
    _2points_attempted INTEGER                                 NOT NULL,
    _2points_made      INTEGER                                 NOT NULL,
    _3points_attempted INTEGER                                 NOT NULL,
    _3points_made      INTEGER                                 NOT NULL,
    ft_attempted       INTEGER                                 NOT NULL,
    ft_made            INTEGER                                 NOT NULL,
    assists            INTEGER                                 NOT NULL,
    steals             INTEGER                                 NOT NULL,
    turnovers          INTEGER                                 NOT NULL,
    rebounds           INTEGER                                 NOT NULL,
    offensive_rebounds INTEGER                                 NOT NULL,
    defensive_rebounds INTEGER                                 NOT NULL,
    plus_minus         INTEGER                                 NOT NULL
);

ALTER TABLE basketball_player_game
ADD CONSTRAINT FK_BASKETBALL_PLAYER_GAME_ON_GAME FOREIGN KEY (game_id) REFERENCES basketball_game (id);

ALTER TABLE basketball_player_game
ADD CONSTRAINT FK_BASKETBALL_PLAYER_GAME_ON_PLAYER FOREIGN KEY (player_id) REFERENCES basketball_player (id);

ALTER TABLE basketball_player_game
ADD CONSTRAINT UNIQUE_PLAYER_GAME_ID UNIQUE (player_id, game_id);