spring:
  config:
    import: optional:file:../.env[.properties]
  datasource:
    url: ${PG_DB_URL}
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    baseline-on-migrate: true

  cloud:
    aws:
      region:
        static: ${LOCALSTACK_REGION}
      credentials:
        accessKey: ${LOCALSTACK_ACCESS_KEY}
        secretKey: ${LOCALSTACK_SECRET_KEY}
      sqs:
        endpoint: ${LOCALSTACK_URL}

euroleague:
  api:
    prefix: ${EUROLEAGUE_API_PREFIX}
    starting-season: ${EUROLEAGUE_API_STARTING_SEASON}

localstack:
  sqs:
    euroleague-players-image-request: ${LOCALSTACK_SQS_EUROLEAGUE_PLAYER_REQUEST}
    euroleague-players-image-response: ${LOCALSTACK_SQS_EUROLEAGUE_PLAYER_RESPONSE}
